-- MySQL Script generated by MySQL Workbench
-- Sat Dec  6 22:38:31 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eventos_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eventos_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eventos_bd` DEFAULT CHARACTER SET utf8 ;
USE `eventos_bd` ;

-- -----------------------------------------------------
-- Table `eventos_bd`.`privilegios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos_bd`.`privilegios` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NULL,
  `modulo_eventos` VARCHAR(1) NOT NULL DEFAULT 'N',
  `modulo_ingressos` VARCHAR(1) NOT NULL DEFAULT 'N',
  `modulo_usuarios` VARCHAR(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos_bd`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos_bd`.`categorias` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos_bd`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos_bd`.`usuarios` (
  `id` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `privilegios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_privilegios_idx` (`privilegios_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_privilegios`
    FOREIGN KEY (`privilegios_id`)
    REFERENCES `eventos_bd`.`privilegios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos_bd`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos_bd`.`evento` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `local` VARCHAR(200) NOT NULL,
  `data_evento` DATE NOT NULL,
  `preco` FLOAT NOT NULL,
  `capacidade_maxima` INT NOT NULL,
  `descricao` VARCHAR(500) NULL,
  `categorias_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_evento_categorias1_idx` (`categorias_id` ASC) VISIBLE,
  CONSTRAINT `fk_evento_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `eventos_bd`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos_bd`.`ingresso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos_bd`.`ingresso` (
  `id` INT NOT NULL,
  `evento_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `quantidade` INT NOT NULL DEFAULT 1,
  `data_compra` DATE NOT NULL,
  `valor_total` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ingresso_evento1_idx` (`evento_id` ASC) VISIBLE,
  INDEX `fk_ingresso_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_ingresso_evento1`
    FOREIGN KEY (`evento_id`)
    REFERENCES `eventos_bd`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingresso_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `eventos_bd`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `eventos_bd`.`privilegios`
-- -----------------------------------------------------
START TRANSACTION;
USE `eventos_bd`;
INSERT INTO `eventos_bd`.`privilegios` (`id`, `nome`, `descricao`, `modulo_eventos`, `modulo_ingressos`, `modulo_usuarios`) VALUES (1, 'Administrador', 'Acesso Total ao Sistema', 'S', 'S', 'S');
INSERT INTO `eventos_bd`.`privilegios` (`id`, `nome`, `descricao`, `modulo_eventos`, `modulo_ingressos`, `modulo_usuarios`) VALUES (2, 'Organizador', 'Pode Gerenciar Eventos', 'S', 'S', 'N');
INSERT INTO `eventos_bd`.`privilegios` (`id`, `nome`, `descricao`, `modulo_eventos`, `modulo_ingressos`, `modulo_usuarios`) VALUES (3, 'Cliente', 'Pode Comprar Ingressos', 'N', 'S', 'N');

COMMIT;


-- -----------------------------------------------------
-- Data for table `eventos_bd`.`categorias`
-- -----------------------------------------------------
START TRANSACTION;
USE `eventos_bd`;
INSERT INTO `eventos_bd`.`categorias` (`id`, `nome`, `descricao`) VALUES (1, 'Show', 'Shows musicais e apresentações');
INSERT INTO `eventos_bd`.`categorias` (`id`, `nome`, `descricao`) VALUES (2, 'Teatro', 'Peças teatrais e espetáculos');
INSERT INTO `eventos_bd`.`categorias` (`id`, `nome`, `descricao`) VALUES (3, 'Esporte', 'Eventos Esportivos');
INSERT INTO `eventos_bd`.`categorias` (`id`, `nome`, `descricao`) VALUES (4, 'Conferência', 'Palestras e workshops');

COMMIT;


-- -----------------------------------------------------
-- Data for table `eventos_bd`.`usuarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `eventos_bd`;
INSERT INTO `eventos_bd`.`usuarios` (`id`, `nome`, `email`, `senha`, `privilegios_id`) VALUES (1, 'Administrador', 'admin@gmail.com', 'f6b2de6b654d5f0f322e6b9b997c1207482ef5185607a053bbef4f4e650405dd1c6c258d1c10b65bd1d40ef7106b03d439f1c742f0a90fefa2cdf94c3502cdc3', 1);

COMMIT;

